FROM $DOCKER_REPO/jetty:9.4.6

WORKDIR /var/lib/jetty

COPY target/mark-6.war $JETTY_BASE/webapps/ROOT.war

COPY src/main/webapp/favicon.ico $JETTY_BASE/webapps/favicon.ico
COPY src/main/webapp/favicon.png $JETTY_BASE/webapps/favicon.png
COPY src/main/webapp/logo.png $JETTY_BASE/webapps/logo.png
COPY src/main/webapp/pratilipi-logo-144px.png $JETTY_BASE/webapps/pratilipi-logo-144px.png

EXPOSE 8080




# COPY target/mark-6.war $JETTY_HOME/start.war
# RUN pwd
# COPY target/mark-6.war $JETTY_BASE/webapps/ROOT.war
# COPY pom.xml pom.xml
# COPY target/mark-6.war $JETTY_HOME/start.war
# COPY target/mark-6 $JETTY_BASE/webapps/ROOT
# RUN ls $JETTY_BASE/webapps
# RUN java -jar start.war
