FROM $DOCKER_REPO/jetty:9.4.6
COPY mark-6.war $JETTY_HOME/start.war
# COPY target/mark-6.war $JETTY_HOME/start.war
# COPY target/mark-6 $JETTY_BASE/webapps/ROOT
# RUN ls $JETTY_BASE/webapps
EXPOSE 8080
